name       : grub2
version    : '2.02'
release    : 25
source     :
    - https://ftp.gnu.org/gnu/grub/grub-2.02.tar.xz : 810b3798d316394f94096ec2797909dbf23c858e48f7b3830826b8daa06b7b0f
homepage   : http://www.gnu.org/software/grub/
license    : GPL-3.0
component  : system.boot
summary    : GRUB Boot Loader
description: |
    GRUB Boot Loader
builddeps  :
    - pkgconfig(devmapper)
    - pkgconfig(freetype2)
    - pkgconfig(liblz4)
    - pkgconfig(liblzma)
strip      : no
rundeps    :
    - os-prober
setup      : |
    unset CFLAGS
    unset LDFLAGS
    unset CXXFLAGS
    %patch -p1 < $pkgfiles/brand.patch
    %configure --disable-werror \
               --enable-device-mapper \
               --disable-efiemu \
               --with-platform="pc" \
               --target="i386"
build      : |
    unset CFLAGS
    unset LDFLAGS
    unset CXXFLAGS
    %make
install    : |
    unset CFLAGS
    unset LDFLAGS
    unset CXXFLAGS
    %make_install
    install -Dm0755 $pkgfiles/update-grub $installdir/usr/sbin/update-grub
    install -Dm0755 $pkgfiles/update-grub2 $installdir/usr/sbin/update-grub2
    install -Dm0644 $pkgfiles/conf/grub $installdir/etc/default/grub
    install -Dm0644 $pkgfiles/splash.tga $installdir/usr/share/backgrounds/splash.tga
    install -Dm0644 $pkgfiles/unicode.pf2 $installdir/usr/share/grub/unicode.pf2
