name       : grub2
version    : 2.0.2_beta2
release    : 24
source     :
    - http://alpha.gnu.org/gnu/grub/grub-2.02~beta2.tar.xz : f6c702b2a8ea58f27a2b02928bb77973cb5a827af08f63db38c471c0a01b418d
homepage   : http://www.gnu.org/software/grub/
license    : GPL-3.0
component  : system.boot
summary    : GRUB Boot Loader
description: |
    GRUB Boot Loader
builddeps  :
    - pkgconfig(liblz4)
rundeps    :
    - os-prober
setup      : |
    unset CFLAGS LDFLAGS CXXFLAGS
    sed -i -e '/gets is a/d' grub-core/gnulib/stdio.in.h
    %patch -p1 < $pkgfiles/brand.patch
    %patch -p1 < $pkgfiles/security/cve-2015-8370.patch
    %configure --disable-werror
build      : |
    unset CFLAGS LDFLAGS CXXFLAGS
    %make
install    : |
    unset CFLAGS LDFLAGS CXXFLAGS
    %make_install
    install -Dm0755 $pkgfiles/update-grub $installdir/usr/sbin/update-grub
    install -Dm0755 $pkgfiles/update-grub2 $installdir/usr/sbin/update-grub2
    install -Dm0644 $pkgfiles/conf/grub $installdir/etc/default/grub
    install -Dm0644 $pkgfiles/splash.tga $installdir/usr/share/backgrounds/splash.tga
    install -Dm0644 $pkgfiles/unicode.pf2 $installdir/usr/share/grub/unicode.pf2
