name       : grub2
version    : '2.04'
release    : 29
source     :
    - git|https://git.savannah.gnu.org/git/grub.git : e7b8856f8be3292afdb38d2e8c70ad8d62a61e10
homepage   : https://www.gnu.org/software/grub/
license    : GPL-3.0-or-later
component  : system.boot
networking : yes # Needed for bootstrap
summary    : GRUB Boot Loader
description: |
    GRUB Boot Loader
builddeps  :
    - pkgconfig(devmapper)
    - pkgconfig(freetype2)
    - pkgconfig(fuse)
    - pkgconfig(liblz4)
    - pkgconfig(liblzma)
strip      : no
rundeps    :
    - os-prober
environment: |
    unset CFLAGS
    unset CXXFLAGS
    unset LDFLAGS
setup      : |
    %patch -p1 < $pkgfiles/brand.patch
    %patch -p1 < $pkgfiles/0001-Fix-default-gnulib-url.patch
    PYTHON=python3 ./bootstrap
    %autogen --disable-efiemu \
             --disable-werror \
             --enable-device-mapper \
             --enable-grub-mount \
             --target="i386" \
             --with-platform="pc"
build      : |
    %make
install    : |
    %make_install
    install -Dm00755 $pkgfiles/update-grub  -t $installdir/usr/sbin
    install -Dm00755 $pkgfiles/update-grub2 -t $installdir/usr/sbin
    install -Dm00644 $pkgfiles/conf/grub    -t $installdir/etc/default
    install -Dm00644 $pkgfiles/splash.tga   -t $installdir/usr/share/backgrounds
    install -Dm00644 $pkgfiles/unicode.pf2  -t $installdir/usr/share/grub
    rm $installdir/etc/grub.d/30_uefi-firmware
