name       : grub2
version    : '2.04'
release    : 26
source     :
    - https://ftp.gnu.org/gnu/grub/grub-2.04.tar.xz : e5292496995ad42dabe843a0192cf2a2c502e7ffcc7479398232b10a472df77d
homepage   : https://www.gnu.org/software/grub/
license    : GPL-3.0-or-later
component  : system.boot
summary    : GRUB Boot Loader
description: |
    GRUB Boot Loader
builddeps  :
    - pkgconfig(devmapper)
    - pkgconfig(freetype2)
    - pkgconfig(liblz4)
    - pkgconfig(liblzma)
strip      : no
rundeps    :
    - os-prober
environment: |
    unset CFLAGS
    unset LDFLAGS
    unset CXXFLAGS
setup      : |
    %patch -p1 < $pkgfiles/brand.patch
    %configure --disable-werror \
               --enable-device-mapper \
               --disable-efiemu \
               --with-platform="pc" \
               --target="i386"
build      : |
    %make
install    : |
    %make_install
    install -Dm00755 $pkgfiles/update-grub $installdir/usr/sbin/update-grub
    install -Dm00755 $pkgfiles/update-grub2 $installdir/usr/sbin/update-grub2
    install -Dm00644 $pkgfiles/conf/grub $installdir/etc/default/grub
    install -Dm00644 $pkgfiles/splash.tga $installdir/usr/share/backgrounds/splash.tga
    install -Dm00644 $pkgfiles/unicode.pf2 $installdir/usr/share/grub/unicode.pf2
